version: '3.8'

networks:
  osticketnet:
    driver: bridge

services:
  web-server:
    container_name: osticket
    build: .
    restart: always
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./osticket:/var/www/html/osticket
      - ./docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - osticketnet
  database:
    image: mysql:5.7
    container_name: osticketdb
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
    networks:
      - osticketnet